import type { Strain, Nutrient, Grow } from './types';
export const MOCK_STRAINS: Strain[] = [
  {
    id: 's1',
    name: 'Blue Dream',
    breeder: 'Humboldt Seed Organization',
    thc: 18,
    cbd: 0.1,
    sativaPercentage: 80,
    floweringTime: 9,
    yield: '600 g/m²',
    height: '150-200 cm',
    nutrientSensitivity: 'medium',
    growthTips: 'Resistant to mold, prefers 18/6 veg light cycle. Benefits from topping to control height.',
  },
  {
    id: 's2',
    name: 'OG Kush',
    breeder: 'Royal Queen Seeds',
    thc: 19,
    cbd: 0.5,
    sativaPercentage: 25,
    floweringTime: 8,
    yield: '450 g/m²',
    height: '90-160 cm',
    nutrientSensitivity: 'high',
    growthTips: 'Sensitive to overfeeding, especially nitrogen. Prefers a stable, dry climate.',
  },
  {
    id: 's3',
    name: 'Girl Scout Cookies',
    breeder: 'Cookie Fam Genetics',
    thc: 28,
    cbd: 0.2,
    sativaPercentage: 40,
    floweringTime: 10,
    yield: '500 g/m²',
    height: '100-180 cm',
    nutrientSensitivity: 'medium',
    growthTips: 'Requires support for heavy colas. Does well with SCROG techniques.',
  },
  {
    id: 's4',
    name: 'Sour Diesel',
    breeder: 'Unknown',
    thc: 22,
    cbd: 0.2,
    sativaPercentage: 90,
    floweringTime: 10,
    yield: '500 g/m²',
    height: '100-130 cm',
    nutrientSensitivity: 'medium',
    growthTips: 'Can stretch significantly during early flower. LST is recommended.',
  },
  {
    id: 's5',
    name: 'Granddaddy Purple',
    breeder: 'Ken Estes',
    thc: 20,
    cbd: 0.1,
    sativaPercentage: 0,
    floweringTime: 9,
    yield: '450 g/m²',
    height: '60-100 cm',
    nutrientSensitivity: 'low',
    growthTips: 'Compact and bushy. Cooler temperatures in late flower can enhance purple hues.',
  },
  {
    id: 's6',
    name: 'White Widow',
    breeder: 'Green House Seeds',
    thc: 19,
    cbd: 0.2,
    sativaPercentage: 60,
    floweringTime: 9,
    yield: '450-500 g/m²',
    height: '60-100 cm',
    nutrientSensitivity: 'low',
    growthTips: 'Very resilient and easy for beginners. Covered in white trichomes.',
  },
  {
    id: 's7',
    name: 'Jack Herer',
    breeder: 'Sensi Seeds',
    thc: 20,
    cbd: 0.1,
    sativaPercentage: 55,
    floweringTime: 10,
    yield: '500 g/m²',
    height: '100-180 cm',
    nutrientSensitivity: 'medium',
    growthTips: 'Multiple phenotypes exist. Some are more sativa-dominant and taller.',
  },
  {
    id: 's8',
    name: 'Northern Lights',
    breeder: 'Sensi Seeds',
    thc: 18,
    cbd: 0.1,
    sativaPercentage: 0,
    floweringTime: 8,
    yield: '500 g/m²',
    height: '100-160 cm',
    nutrientSensitivity: 'low',
    growthTips: 'A classic, robust strain. Low odor during growth.',
  },
  {
    id: 's9',
    name: 'Gorilla Glue #4',
    breeder: 'GG Strains LLC',
    thc: 25,
    cbd: 0.1,
    sativaPercentage: 50,
    floweringTime: 9,
    yield: '550 g/m²',
    height: '130-180 cm',
    nutrientSensitivity: 'high',
    growthTips: 'Extremely sticky resin. Can be sensitive to nutrient burn.',
  },
  {
    id: 's10',
    name: 'AK-47',
    breeder: 'Serious Seeds',
    thc: 20,
    cbd: 1.5,
    sativaPercentage: 65,
    floweringTime: 9,
    yield: '350-500 g/m²',
    height: '80-140 cm',
    nutrientSensitivity: 'medium',
    growthTips: 'Strong smell; good ventilation is a must. Easy to grow.',
  },
];
export const MOCK_NUTRIENTS: Nutrient[] = [
  {
    id: 'n1',
    brand: 'FoxFarm',
    name: 'Grow Big',
    npk: '6-4-4',
    stage: 'veg',
    dosage: '2-3 tsp/gal',
    applicationFrequency: 'Every other watering',
  },
  {
    id: 'n2',
    brand: 'FoxFarm',
    name: 'Tiger Bloom',
    npk: '2-8-4',
    stage: 'flower',
    dosage: '2-3 tsp/gal',
    applicationFrequency: 'Every other watering',
  },
  {
    id: 'n3',
    brand: 'FoxFarm',
    name: 'Big Bloom',
    npk: '0-0.5-0.7',
    stage: 'supplement',
    dosage: '4 tbsp/gal',
    applicationFrequency: 'Every watering',
    mixingInstructions: 'Can be used throughout the entire grow cycle.',
  },
  {
    id: 'n4',
    brand: 'General Hydroponics',
    name: 'FloraMicro',
    npk: '5-0-1',
    stage: 'supplement',
    dosage: '1/4 - 2 tsp/gal',
    mixingInstructions: 'Part of the 3-part Flora Series. Add to water first.',
  },
  {
    id: 'n5',
    brand: 'General Hydroponics',
    name: 'FloraGro',
    npk: '2-1-6',
    stage: 'veg',
    dosage: '1/4 - 3 tsp/gal',
    mixingInstructions: 'Part of the 3-part Flora Series.',
  },
  {
    id: 'n6',
    brand: 'General Hydroponics',
    name: 'FloraBloom',
    npk: '0-5-4',
    stage: 'flower',
    dosage: '1/4 - 3 tsp/gal',
    mixingInstructions: 'Part of the 3-part Flora Series.',
  },
  {
    id: 'n7',
    brand: 'Advanced Nutrients',
    name: 'pH Perfect Sensi Grow Part A',
    npk: '3-0-0',
    stage: 'veg',
    dosage: '4ml/L',
    warnings: 'Use with Part B.',
  },
  {
    id: 'n8',
    brand: 'Advanced Nutrients',
    name: 'Bud Candy',
    npk: '0-0-1',
    stage: 'boost',
    dosage: '2ml/L',
    applicationFrequency: 'Weeks 1-6 of flower.',
  },
  {
    id: 'n9',
    brand: 'Botanicare',
    name: 'Cal-Mag Plus',
    npk: '2-0-0',
    stage: 'supplement',
    dosage: '1 tsp/gal',
    warnings: 'Essential for coco coir and LED grows.',
  },
  {
    id: 'n10',
    brand: 'Super Thrive',
    name: 'Vitamin Solution',
    npk: '0.5-0-0',
    stage: 'supplement',
    dosage: '1 drop/gal',
    mixingInstructions: 'Reduces transplant shock and stress.',
  },
];
export const MOCK_GROWS: Grow[] = [
    {
        id: 'g1',
        name: 'First Grow - Blue Dream',
        userId: 'u1',
        strainId: 's1',
        startDate: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
        plantCount: 4,
        environmentNotes: 'Indoor tent, 600W HPS, FoxFarm Ocean Forest soil.',
        logs: [],
    },
    {
        id: 'g2',
        name: 'OG Kush Experiment',
        userId: 'u1',
        strainId: 's2',
        startDate: new Date(new Date().setDate(new Date().getDate() - 45)).toISOString(),
        plantCount: 2,
        environmentNotes: 'Hydroponic DWC setup.',
        logs: [],
    },
    {
        id: 'g3',
        name: 'GSC Scrog',
        userId: 'u1',
        strainId: 's3',
        startDate: new Date(new Date().setDate(new Date().getDate() - 70)).toISOString(),
        plantCount: 1,
        environmentNotes: '4x4 tent with SCROG net.',
        logs: [],
    }
];